### PR TITLE
cmake: Forward CMAKE_BUILD_TYPE to Arrow

### PR DESCRIPTION
**Pull request by felipecrv**
But not DuckDB because then the build fails for some reason.

### CODE REVIEW

**Review by prmoore77 — APPROVED** [review]

**Comment by prmoore77** [comment]
actually - the builds are failing - can you take a look, @felipecrv ?

**Comment by felipecrv** [comment]
I'm setting it explicitly now which seems to be the right thing to do since the docs are very unclear about the value it would have without being set.

https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by felipecrv** [comment]
I will be trying many different things to make these builds pass. 😓

**Comment by felipecrv** [comment]
I will try to simplify the build before making it possible to build this project with Arrow built in Debug mode.

**Pull request closed without merging**
